import { Router } from 'express';
import authRoutes from './auth.js';
import cplRoutes from './cpl.js';
import cplMappingRoutes from './cpl-mapping.js';
import mataKuliahRoutes from './mata-kuliah.js';
import dashboardRoutes from './dashboard.js';
import usersRoutes from './users.js';
import nilaiCplRoutes from './nilai-cpl.js';
import profileRoutes from './profile.js';
import transkripCplRoutes from './transkrip-cpl.js';
import transkripCpmkRoutes from './transkrip-cpmk.js';
import cpmkRoutes from './cpmk.js';
import cpmkMappingRoutes from './cpmk-mapping.js';
import teknikPenilaianRoutes from './teknik-penilaian.js';
import nilaiTeknikRoutes from './nilai-teknik.js';
import settingsRoutes from './settings.js';
import mataKuliahPengampuRoutes from './mata-kuliah-pengampu.js';
import kaprodiDataRoutes from './kaprodi-data.js';
import fakultasRoutes from './fakultas.js';
import prodiRoutes from './prodi.js';
import kurikulumRoutes from './kurikulum.js';
import jenisMataKuliahRoutes from './jenis-mata-kuliah.js';
import kategoriCplRoutes from './kategori-cpl.js';
import levelTaksonomiRoutes from './level-taksonomi.js';
import teknikPenilaianRefRoutes from './teknik-penilaian-ref.js';
import referencesRoutes from './references.js';
import rubrikRoutes from './rubrik.js';
import evaluasiRoutes from './evaluasi.js';
import angkatanRoutes from './angkatan.js';
import visiMisiRoutes from './visi-misi.js';
import profilLulusanRoutes from './profil-lulusan.js';
import kuesionerRoutes from './kuesioner.js';
import subCpmkRoutes from './sub-cpmk.js';
import transkripProfilRoutes from './transkrip-profil.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/cpl', cplRoutes);
router.use('/cpl-mata-kuliah', cplMappingRoutes);
router.use('/mata-kuliah', mataKuliahRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', usersRoutes);
router.use('/nilai-cpl', nilaiCplRoutes);
router.use('/profiles', profileRoutes);
router.use('/transkrip-cpl', transkripCplRoutes);
router.use('/transkrip-cpmk', transkripCpmkRoutes);
router.use('/cpmk', cpmkRoutes);
router.use('/cpmk-mapping', cpmkMappingRoutes);
router.use('/teknik-penilaian', teknikPenilaianRoutes);
router.use('/nilai-teknik', nilaiTeknikRoutes);
router.use('/settings', settingsRoutes);
router.use('/mata-kuliah-pengampu', mataKuliahPengampuRoutes);
router.use('/kaprodi-data', kaprodiDataRoutes);
router.use('/fakultas', fakultasRoutes);
router.use('/prodi', prodiRoutes);
router.use('/kurikulum', kurikulumRoutes);
router.use('/jenis-mata-kuliah', jenisMataKuliahRoutes);
router.use('/kategori-cpl', kategoriCplRoutes);
router.use('/level-taksonomi', levelTaksonomiRoutes);
router.use('/teknik-penilaian-ref', teknikPenilaianRefRoutes);
router.use('/references', referencesRoutes);
router.use('/rubrik', rubrikRoutes);
router.use('/evaluasi', evaluasiRoutes);
router.use('/angkatan', angkatanRoutes);
router.use('/visi-misi', visiMisiRoutes);
router.use('/profil-lulusan', profilLulusanRoutes);
router.use('/kuesioner', kuesionerRoutes);
router.use('/sub-cpmk', subCpmkRoutes);
router.use('/transkrip-profil', transkripProfilRoutes);

export default router;
